title: <p align="center"> Shahad Qathan </p>
logo: /assets/img/p.png
description: <p align="center">
  <a href="assets/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shahad-qathan/">LinkedIn</a> |
  <a href="https://github.com/shalabs">GitHub</a>
  </p>
  
  <p align="justify">
  Interested in applying Artificial Intelligence and Data Science in bioinformatics and healthcare to solve complex problems.
  </p>

long_description: Software Engineer and AI researcher*
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
